---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robo
  template:
    metadata:
      labels:
        app: robo
    spec:
      containers:
      - name: robo
        image: ealtedge/robo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: robo-service
spec:
  type: NodePort
  selector:
    app: robo
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 80
    nodePort: 30001
