- name: Import vars
  include_vars:
  # yamllint disable rule:line-length
      file: /root/edgeakraino/jenkins/work/workspace/ealt-edge-deploy-virtual-daily-master/ocd/infra/playbooks/config.yml
  # yamllint disable rule:line-length
      name: vardata

- name: Pull helm chart appstore
  # yamllint disable rule:line-length
  command: helm install appstore-edgegallery edgegallery/appstore --set global.oauth2.authServerAddress=https://{{vardata.authServerMecm.name}}:30067 --set global.ssl.enabled=true --set global.ssl.secretName=edgegallery-ssl-secret
