---

firstvar:
  name: te9Fmv%qaq
secondvar:
  name: two
swrusr:
  name: ap-southeast-1@0K1RQ5EAF2QRKQWQNFY0
swrpass:
  name: 5468d8a0ebc64936a8196742d601bb95b99f1d94ad19c686488831e3dae79bb3
sUserName:
  name: admin
sPass:
  name: admin123
authServer:
  name: 10.10.0.202
authServerMecm:
  name: 119.8.41.103
