# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

swrusr:
  name:
swrpass:
  name:
cert_validity_in_days:
  name:
mecm_meo_db_password:
  name:
mecm_mepm_db_password:
  name:
dockerusr:
  name:
dockerpass:
  name:
secret_keystorepass:
  name:
secret_cert_pass:
  name:
private_repo_ip:
  name:
mep_pg_admin_pwd:
  name:
mep_kong_pg_pwd:
  name:
mep_cert_pwd:
  name:
system_interfaceeth1:
  name:
system_interfaceeth2:
  name:
mep_ip_addr_macvlan_eg_mep1:
  name:
mep_ip_addr_mm5_eg_mm5:
  name:
mep_image_tag:
  name:
mep_mepauth_image_tag:
  name:
mep_dns_image_tag:
  name:
generate_cert_pass:
  name:
mecm_mepm_postgresPassword:
  name:
mecm_mepm_postgresLcmCntlrPassword:
  name:
mecm_mepm_postgresk8sPluginPassword:
  name:
mecm_mepm_lcmcontroller_image_tag:
  name:
mecm_mepm_k8splugin_image_tag:
  name:
mecm_mepm_postgres_image_tag:
  name:
user_mgmt_encryptpass:
  name:
user_mgmt_oauth_appstore_client_ip:
  name:
user_mgmt_oauth_developer_client_ip:
  name:
user_mgmt_oauth_mecm_client_ip:
  name:
user_mgmt_image_tag:
  name:
mecm_meo_keystorePassword:
  name:
mecm_meo_truststorePassword:
  name:
mecm_meo_postgresPassword:
  name:
mecm_meo_postgresApmPassword:
  name:
mecm_meo_postgresAppoPassword:
  name:
mecm_meo_postgresInventoryPassword:
  name:
mecm_meo_edgeRepoUserName:
  name:
mecm_meo_edgeRepoPassword:
  name:
mecm_meo_image_tag:
  name:
mecm_meo_appo_image_tag:
  name:
mecm_meo_apm_image_tag:
  name:
mecm_meo_postgres_tag:
  name:
mecm_meo_fsgroup:
  name:
mecm_fe_centernodeip:
  name:
mecm_fe_image_tag:
  name:
appstore_centernodeip:
  name:
appstore_fe_image_tag:
  name:
appstore_be_image_tag:
  name:
developer_centernodeip:
  name:
developer_fe_image_tag:
  name:
developer_be_image_tag:
  name:
